name: build-and-test
on:
  push:
    branches:
      - '**'
jobs:
  build-and-test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cehckout@v2
      - run: gcc hw.c
      - run: ./a.out
